### ISSUE TITLE
TintColor and FloatingPlaceholderColor

### ISSUE THREAD

**Issue by thiagoparabas** [BaseflowIT/XF-Material-Library#113]
When we insert the tintcolor color the floatingplaceholder color is overwrite, the correct one is to have separate colors, because when we want the color of the line to be transparent we inform the tintcolor as transparent also affecting the floatingplaceholdercolor.

A color for the flatingplaceholdercolor has already been set, even though it does not apply.

Version 1.4.1.1

**Comment by contrix09** [comment]
The `TintColor` is applied to the floating placeholder and the underline indicator when the text field is focused. The `FloatingPlaceholderColor` will only be applied if the text field is not focused and the text field has text. If you want to not show the underline indicator when the text field is focused, use the `ShouldAnimateUnderline` property.

You can see the states of the text field below, per Material Guidelines:
![image](https://user-images.githubusercontent.com/29834445/54080369-0d74f680-4329-11e9-84e3-919ee81aae04.png)

**Comment by moreirawebmaster** [comment]
If ShouldAnimateUnderline property is false not show icon error and errortext. I using icon error and TextError, I can not disabled ShouldAnimateUnderline.

**Comment by thiagoparabas** [comment]
@contrix09 
Setting ShouldAnimateUnderline so true FloatingPlaceholder not working and icon error and errotext too.

**Comment by OdetteP** [comment]
Did you solve this issue?
