### ISSUE TITLE
MaterialTextField in MaterialCard Bound not working

### ISSUE THREAD

**Issue by muhammetsahin** [BaseflowIT/XF-Material-Library#122]
**Describe the bug**
Here is my code material text field not bound with cardview

` <StackLayout
      Padding="5,0,5,5" Spacing="5"
      HorizontalOptions="FillAndExpand"
      Orientation="Horizontal"
      VerticalOptions="FillAndExpand">
              <material:MaterialCard BackgroundColor="Red" 
                                     BorderColor="White" 
                                     CornerRadius="10"
                                     Elevation="0" HorizontalOptions="FillAndExpand"
                                   
                                     IsClickable="false">
                            <material:MaterialTextField 
                    
                    AlwaysShowUnderline="false" 
                    BackgroundColor="White" 
                    FloatingPlaceholderEnabled="False" 
                    HorizontalPadding="0"
                    InputType="Text"  
                    IsAutoCapitalizationEnabled="false"
                    IsMaxLengthCounterVisible="false" 
                    MaxLength="50"
                    Placeholder="{i18n:Translate SearchPageSearchEntryPlaceholder}"
                   LeadingIcon="ic_magnify_white_24dp.png"
                    LeadingIconTintColor="{DynamicResource CandelitGray1}"
                       PlaceholderColor="{DynamicResource CandelitGray1}"
                PlaceholderFontFamily="{StaticResource LifeFontFamily}" 
                ReturnType="Search"
                ShouldAnimateUnderline="false" 
                TextColor="{StaticResource CandelitGray1}" 
                TextFontFamily="{StaticResource LifeFontFamily}"
                TintColor="{StaticResource CandelitGray1}" />
                        </material:MaterialCard>
     
     
      <material:MaterialLabel
        Text="{i18n:Translate ShowAlertConfirmButtonCancelText}"
        FontSize="{StaticResource MidMediumSize}"
        TextColor="White" HorizontalOptions="End"
        FontFamily="{StaticResource LifeFontFamily}"
        TextDecorations="None" 
        VerticalOptions="Center">
                 <material:MaterialLabel.GestureRecognizers>
            <TapGestureRecognizer Command="{Binding ClearSearchTextCommand}" NumberOfTapsRequired="1" />
          </material:MaterialLabel.GestureRecognizers>
                
            </material:MaterialLabel>
    </StackLayout>`

Here is ios screenshot
![Simulator Screen Shot - iPhone 6 - 2019-03-17 at 16 32 02](https://user-images.githubusercontent.com/2045788/54491793-36216100-48d2-11e9-8263-c4f0c02b010d.png)

and android:
![image](https://user-images.githubusercontent.com/2045788/54491831-88628200-48d2-11e9-92d8-89ae095f879a.png)

Im using XF.Material version 1.4.1.1 

Thanks.

**Comment by OdetteP** [comment]
Did you solve this issue?
