### ISSUE TITLE
MaterialButton add multiline support for iOS

### ISSUE THREAD

**Issue by PaulP92** [BaseflowIT/XF-Material-Library#124]
**Is your feature request related to a problem? Please describe.**
Longer text is always middle truncated. I would like to have an option where the text wraps on a new line, like on android devices.

**Describe the solution you'd like**
Add a LinebreakMode property for MaterialButton or make LinebreakMode WordWrap default for the TextLabel

**Describe alternatives you've considered**
I've tried to implement a custom renderer for MaterialButton, with no success. 

Thanks!

**Comment by fabcall** [comment]
According to Material Design guidelines, text inside buttons shouldn't be wrapped, so, I'm not sure your proposal wouldn't be considered an anti-pattern.
