### ISSUE TITLE
Showing Grey background in material select choice async method in android.

### ISSUE THREAD

**Issue by vjsystematix** [BaseflowIT/XF-Material-Library#138]
I am using XF Material 1.4.1.3 Material library and I am using Material select choices async method. In android functioning works well but UI shows grey in color. I have checked in all android devices.

Attache the screen shot  
![Screen Shot 2019-03-30 at 4 13 10 PM](https://user-images.githubusercontent.com/22585811/55275088-f06b8c00-5306-11e9-8f81-ae6d45f0c99c.png)
can you please help me on this..

**Comment by vjsystematix** [comment]
@contrix09 

Any update on this, might be some issue for setting style.

**Comment by vjsystematix** [comment]
Anyone can help me on this as i have a release and need to put the app on store.

Thanks

**Comment by vjsystematix** [comment]
@contrix09 

Can you please help me on this , my release is stuck due to this.
Thanks

**Comment by vjsystematix** [comment]
@contrix09 
Please check this one, as can't upgrade android on 9.0

**Comment by OdetteP** [comment]
Did you resolve the issue in the end?
