### ISSUE TITLE
LoadDialogAsync cannot be dismissed

### ISSUE THREAD

**Issue by PaulITD** [BaseflowIT/XF-Material-Library#151]
**Describe the bug**
The LoadDialog cannot be dismissed.

I have a property set which starts the LoadDialog when true. When false, it should dismiss

**To Reproduce**
Create a page and add the LoadDialogAsync using

var materialPage = await MaterialDialog.Instance.LoadingModalDialogAsync(message: "some text");
await Task.Delay(500);
await materialPage.DismissAsync();

**Expected behavior**
The modal should dismiss when the dismiss is called

**Smartphone (please complete the following information):**
 - Device: Android emulator, iOS simulator
 - OS: Pie & Oreo, OS 12.2
 - Version 1.4.1.3

**Comment by JamesJohn93** [comment]
I noticed the same thing using a _using_ to handle the dialog.

`using (_dialogService.ShowLoadingToast("loading. Please wait..."))
                {
                    await SomeAsyncCall(lookupType, data).ContinueWith((data) => DoSomthingWithTheData(data)); 
                } `

**Comment by sarthak199526** [comment]
Yes Please do something about this bug though it's work on older version OS

**Comment by OdetteP** [comment]
Is this still an issue? I tried to reproduce it but for me it works fine
