### ISSUE TITLE
MaterialTextField background Transparent

### ISSUE THREAD

**Issue by lumisoftusa** [BaseflowIT/XF-Material-Library#155]
**Describe the bug**
MaterialTextField background Transparent does not work if i use background image.

**To Reproduce**

**Expected behavior**
I am using MaterialTextField with background image i want transparent background with default bottom border color white.

**Screenshots**
 
![Untitled](https://user-images.githubusercontent.com/5659771/58264380-3426c300-7d97-11e9-9298-45bb946f4473.png)

**Comment by OdetteP** [comment]
I am trying to reproduce it, but how did you get a background Image on a MaterialTextField?
