### ISSUE TITLE
MaterialDialog "OK" button disabled in IOS

### ISSUE THREAD

**Issue by GTripathee** [BaseflowIT/XF-Material-Library#157]
**Describe the bug**
I am using _MaterialDialog.Instance.InputAsync()_ to create the material dialog . After I type something in text field, I can perform the confirming Text (OK) button operation, but the Color is not changing from the light gray to the desired color.

**To Reproduce**
1. use  _MaterialDialog.Instance.InputAsync()_ and give arguments
2. open the app in IOS
3. type something
4. Ok  color wont change

**Expected behavior**
After typing, I need the primary color in the OK button 
OR
 **Color of the Confirming text need to be enabled**

**Screenshots** 
<img width="265" alt="Annotation 2019-05-28 165438" src="https://user-images.githubusercontent.com/15964340/58488282-648ca980-8169-11e9-917e-b56ac4c0ef67.png">

**Smartphone **
 - IOS 12.2
 - .

**Comment by DavidGonzAlv** [comment]
Im also facing this issue.

**Comment by GLDima** [comment]
> I can confirm that I am also experiencing this.
> 
> It also seems to happen on a **MaterialTextField** which has **InputType="Choice"**. When you select a radio button, the OK button remains grayed out, I would expect it to light up with the same color as the Cancel button once a choice has been made.

Take a look at this fix https://github.com/contrix09/XF-Material-Library/commit/a7a5b61bbf2c0710be4157fa306366dab9f3a0fe

**Comment by Pepsi1x1** [comment]
This is not the correct fix for this issue, using this fix the OK button becomes available when no selection has been made. The correct fix for this is setting the styles for the appropriate control states in the iOS MaterialButtonRenderer

**Comment by Pepsi1x1** [comment]
See https://github.com/Pepsi1x1/XF-Material-Library/commit/6eaa99f7080a8d81c520112fe9a84702bc0764dd

**Comment by martijn00** [comment]
@Pepsi1x1  can you open a PR with your fix?
