### ISSUE TITLE
MaterialMenuButton does not show three dots instead shows the MaterialButton like designs.

### ISSUE THREAD

**Issue by aditya41295** [BaseflowIT/XF-Material-Library#159]
<material:MaterialMenuButton ButtonType="Text" CornerRadius="24" Choices="{Binding Actions}" Command="{Binding MenuCommand}" /> 
used this in the xaml, but the three dots as shown in the preview are not coming, instead the button styling is coming.

**Comment by OdetteP** [comment]
I have reproduced the findings and found that the MaterialMenuButton is by default a button. If you want an image like in the sample you need to provide the image.
