### ISSUE TITLE
SelectChoice TintColor on Confirm Button not working on iOS

### ISSUE THREAD

**Issue by JimmyPun610** [BaseflowIT/XF-Material-Library#160]
**Describe the bug**
SelectChoice TintColor on Confirm Button not working

**To Reproduce**
1. Use SelectChoice create example
2. Confirm button in iOS version always Gray(like disabled)

**Expected behavior**
Confirm button will have color.

**Smartphone (please complete the following information):**
iPhone 6s with iOS 12

**Comment by DavidGonzAlv** [comment]
Im stuck with this issue too.
