### ISSUE TITLE
Custom Behavior MaterialTextField

### ISSUE THREAD

**Issue by winnertech** [BaseflowIT/XF-Material-Library#162]
Not is possible setting custom Behavior.
MaterialTextField is ContentView this behavior custom is Entry.
Please exists possibilite customizing?

**Comment by OdetteP** [comment]
Can you please  be a bit more specific in what it that you want to achieve. Do you have some code to share? Thank you!

**Comment by Deepfreezed** [comment]
OP want to have custom Behaviors. Behaviors only applies views (controls), and not to pages(ContentPage). MaterialTextField acts as an Entry but Behavior cannot be attached to it since it's ContentPage.

Behaviors are useful when you want to support input mask for an Entry control.

**Comment by Deepfreezed** [comment]
OP want to support custom Behaviors. MaterialTextField is ContentView (i.e: custom control).

You can do something link below for custom Behaviors:
```
        protected override void OnAttachedTo(MaterialTextField view)
        {           
            view.TextChanged += OnEntryTextChanged;
            base.OnAttachedTo(view);
        }

        protected override void OnDetachingFrom(MaterialTextField view)
        {  
            view.TextChanged -= OnEntryTextChanged;
            base.OnDetachingFrom(view);
        }
```
