### ISSUE TITLE
Object reference not set to an instance of an object on material button in iOS

### ISSUE THREAD

**Issue by SomValentino** [BaseflowIT/XF-Material-Library#174]
**Describe the bug**
When running my app on the iOS platform when I click on a material button I get the error as described in the issue title.

**To Reproduce**
Declared a material button in my xaml file as follows:
ContentPage Header
`xmlns:material="clr-namespace:XF.Material.Forms.UI;assembly=XF.Material.Forms"`

`<material:MaterialButton Grid.Row="0" Text="Login"
                                             BackgroundColor="{StaticResource LightForeground}"
                                             TextColor="{StaticResource ProfileBackgroundColor}"
                                             CornerRadius="6"
                                             Elevation="8"
                                             ButtonType="Elevated">
                           <Button.Behaviors>
                               <behaviors:EventToCommandBehavior EventName="Clicked" Command="{Binding LoginCommand}"/>
                           </Button.Behaviors>
                    </material:MaterialButton>`

When I click on the material button to navigate to another page I get the above error as mentioned in the issue title. Below is the stack trace

`"  at XF.Material.iOS.Renderers.MaterialButtonRenderer.Control_Released (System.Object sender, System.EventArgs e) [0x0005c] in /Users/vsts/agent/2.148.2/work/1/s/XF.Material/XF.Material.iOS/Renderers/MaterialButtonRenderer.cs:167 \n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 \n  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/Foundation/NSAction.cs:178 "`

I have declared the init fuctions in android and iOS platforms as follows:

Android

`XF.Material.Droid.Material.Init(this, savedInstanceState);
  Rg.Plugins.Popup.Popup.Init(this, savedInstanceState);`

IOS

`XF.Material.iOS.Material.Init();
  Rg.Plugins.Popup.Popup.Init();`

**Expected behavior**
I shouldn't get this error when I click on a material button running on iOS platform

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhoneXe iOS 12.4 simulator
 
**Additional context**
However note I don't get this error in my android project but occurs in my iOS project.

**Comment by mtsrdr** [comment]
The same thing happened to me.

**Comment by mtsrdr** [comment]
The same thing happened to me.

A temporarily solution is to put a small delay before navigating to another page if the RuntimePlatform is iOS until this issue gets solved:



        private async Task LogIn()
        {
            if(_deviceService.RuntimePlatform == RuntimePlatform.iOS)
            {
                await Task.Run(() => Task.Delay(100));
            }
            await NavigationService.NavigateAsync("/MainPage");
        }
