### ISSUE TITLE
XF.Material.Droid is missing ? 

### ISSUE THREAD

**Issue by jm-parent** [BaseflowIT/XF-Material-Library#176]
**Describe the bug**
It seems XF.Material.Droid is missing ? 
IOS and forms init are ok.

Can't use this in MainActivity :)
XF.Material.Droid.Material.Init(this, bundle);

And this is my object Explorer
https://i.imgur.com/2oNugR0.png

Tried with 1.4.1.3 and 1.4.1.1 ( i saw other project using 1.4.1.3 without any problem )

**Expected behavior**
Droid.Init works ✌️

**Comment by mschmidt-healthx** [comment]
+1, dropping back to 1.3.1.1 works fine.
