### ISSUE TITLE
MaterialTextField Placeholder not hiding when manually set text property

### ISSUE THREAD

**Issue by RonnyBansemer** [BaseflowIT/XF-Material-Library#178]
**Describe the bug**
There are two bugs relating the placeholder:
1.) The placeholder does not hide when setting materialEntry.Text to a non-null and non-empty string.
2.) The placeholder does not hide when focusing the text field previously valued using materialEntry.Text.
First I thought it was a non-mainthread-related problem, but the error even occours setting on mainthread. Tested on Android 5.1 and 9.

**To Reproduce**
1. Create a MaterialTextField
2. Give it a name... in my case passwordEntry
3. Execute the following code on a mainthread-called method, e.g. OnAppearing in ContentPage

```c#
passwordEntry.Text = "foo";

Task.Delay(TimeSpan.FromMilliseconds(500))
        .ContinueWith(_ =>
        {
           MainThread.BeginInvokeOnMainThread(() =>
           {
              passwordEntry.Text = string.Empty;
              passwordEntry.Unfocus();
              passwordEntry.Text = "bar";
            });

            Task.Delay(TimeSpan.FromMilliseconds(500))
                    .ContinueWith(b =>
                    {
                       MainThread.BeginInvokeOnMainThread(() =>
                       {
                          passwordEntry.Focus();
                       });
                    });
         });
```

**Expected behavior**
Placeholder should shrink and move when value is set.

**Comment by OdetteP** [comment]
I have reproduced it with your code, but in my case the placeholder shrinks as expected. Can you tell me more about how you used it?

**Comment by OdetteP** [comment]
I have reproduced your code reproduced and found that if you remove this line of code               passwordEntry.Text = string.Empty;  it will work as expected.

**Comment by fgbustoa** [comment]
OdetteP,

are you sure it works ??? Try to assign a string value to a bounded property ....

![Annotazione 2020-03-08 164735](https://user-images.githubusercontent.com/55985383/76166136-8eddaf80-615c-11ea-8a54-1fa2393c4695.png)

1) the 2 textfields had text property = ""
2) From ViewModel a set a value to bounded properties, and that's the result
