### ISSUE TITLE
MaterialTextField ErrorText remains after setting HasError to false

### ISSUE THREAD

**Issue by RonnyBansemer** [BaseflowIT/XF-Material-Library#179]
**Describe the bug**
I have a MaterialTextField with a helper text.
After I set HasError true and ErrorText to a string on MaterialTextField the helper text is replaced by the error message with a red color. Until now thats the expected behavior.
But After setting HasError to false the error text still remains, just the color changed from red to helper text color. 

**Expected behavior**
After setting HasError to false, the error text should be removed or in case there is a helper text it should replaced by them.

**Comment by Miiite** [comment]
Can't reproduce it on the latest version for both iOS and Android. You might need to show some code to reproduce the issue
