### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by martani** [BaseflowIT/XF-Material-Library#76]
Hi,

Does this work for Xamarin Forms on MacOS (https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status).

If not, what's the scale of changes needed to have a basic version working on MacOS?

**Comment by contrix09** [comment]
Hi, I'm sorry but this library does not support MacOS. I don't know the scale of changes because I have no development experience in MacOS.

**Comment by martijn00** [comment]
Basic support is included in 1.5.0. Please open a PR with more support in this folder if you want to help: https://github.com/BaseflowIT/XF-Material-Library/tree/develop/XF.Material/Platforms
