### ISSUE TITLE
The type or namespace name 'Droid' does not exist in the namespace 'XF.Material'

### ISSUE THREAD

**Issue by luisnovais23** [BaseflowIT/XF-Material-Library#99]
After 1.4.0.1 version when try to inicialize in android MainActivity I get this error.
Can you see what is wrong in your nuget ?

**Comment by contrix09** [comment]
Hi. Since 1.4.0.0, the target framework version for Android has been changed to `v9.0`, make sure your project also targets the same version. You need to make sure also your `Xamarin.Android.Support.*` NuGet packages are version `28.0.0`. You can refer to this [issue](https://github.com/contrix09/XF-Material-Library/issues/79).

**Comment by avalosleonardo** [comment]
So, I'm having the same issue, and I've tried to set the target Android version to 9.0, as well as made sure all the Xamarin.Android.Support.* were up to date (they were, at 28.0.0.1). I'm using the latest version of XF.Material (1.4.1.1) and even tried lowering it to the version on the question, but still not luck. Could there be anything else I might be missing?
<img width="469" alt="Screen Shot 2019-03-14 at 2 15 12 PM" src="https://user-images.githubusercontent.com/48567813/54385003-9a8ab900-4663-11e9-8960-4e3cd0660a9e.png">

**Comment by breakcoding** [comment]
I have the same problem, the target of Android is 9.0, and I used the last version 1.4.1.1 and for Support.* is 28.0.0.1, what's we need to do?

**Comment by contrix09** [comment]
Hi all, please try to uninstall all nuget packages then install first `XF.Material` package since it automatically references `Xamarin.Forms` as well as the other `Xamarin.Android.Support.*` packages that `Xamarin.Forms` is using. Then install the other packages. Try to see also the output window for any errors or warnings regarding target framework mismatch. I'll further investigate on this issue.

**Comment by sirlordt** [comment]
Same issue with me 

XF.Material.Droid.Material.Init(this, savedInstanceState); 

This lines have problems.

I have new project no code added, no anothers libraries, only this library, blank project from scratch, using net standard project. I using VS Comunity 2017, I upgraded NuGet packages from Ximarin.Forms from 3.4.0. to 3.5.0.274416 in main project and Android and IOS project.

I uninstall and install the package and get same error.

xf.material: 1.4.1.3

Microsoft Visual Studio Community 2017 
Version 15.9.10
VisualStudio.15.Release/15.9.10+28307.557
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA676
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GorillaPlayerPackage Extension   1.0
GorillaPlayerPackage Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.28307.556
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.81 (d15-9@780082716)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.16 (2dc06c7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by contrix09** [comment]
Hi, please be sure to update all necessary `Xamarin.Android.Support.*` libraries to the latest version `28.0.0.*`.

Here is a sample project: 
[SampleApp.zip](https://github.com/contrix09/XF-Material-Library/files/3025240/SampleApp.zip)

**Comment by lywyn** [comment]
Updated everything still get the error. Cannot remove Xamarin.Forms nuget dependency as required by other packages/code too.

**Comment by Luismimultimedia** [comment]
Hello,

i am facing the same issue, the error says "it doesnt found Droid in the name space 'XF.Material'".
my package nugets are :
Xamarin.Forms v4.5.0.396
Xamarin.Essentials v1.5.1
XF.Material v1.6.1
Xamarin.Android.Support.* v28.0.0.3

My target android is Android10, Api 29 (Q)

I also download #57 (comment) the example and i update on the version of Xamarin.Forms and XF.Material i have and the problem perssist.

I hope if someone can help me, i will be so glad.

Thank you.

**Comment by jenssmeds** [comment]
@Luismimultimedia I had the same problem with an almost identical setup. Got it working by downgrading XF.Material to 1.5.8.

**Comment by Luismimultimedia** [comment]
@jenssmeds Thanks, im going to try it and see how is going on, at the momento i downgrading XF.Material to 1.4.0.1 but in IOS the selectChoiseAsycn method it doesnt work, it tell me that the cast is invalid. i hope your solution helps me.

**Comment by Luismimultimedia** [comment]
@jenssmeds Hey great news, it works perfectly and also its working on IOS, now i have to fix the modal that is opening the method SelectChoiseAsync.

Thank you so much for the help, if someone have the same problem this is my setup 

Xamarin.Forms v4.5.0.396
Xamarin.Essentials v1.5.1
XF.Material v1.5.8
Xamarin.Android.Support.* v28.0.0.3

My target android is Android10, Api 29 (Q)

**Comment by ianvink** [comment]
I found downgrading to 1.5.8 worked for me too. I have Support 28.0.0.3 and build with Android 10 Q

**Comment by assemhakmeh** [comment]
I'm having the same issue with 1.6.4 on a new project in VS Mac, TF -> Android 10. Support 28.0.0.3.
